// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIHscjlVILrRxwbhlEcgptQq2NZKhxamg',
    appId: '1:69808295537:web:8186d05dfb5825966e95d0',
    messagingSenderId: '69808295537',
    projectId: 'new-application-2fdd1',
    authDomain: 'new-application-2fdd1.firebaseapp.com',
    storageBucket: 'new-application-2fdd1.appspot.com',
    measurementId: 'G-BJQB5ENC9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfIpxsjlK-id4RQV54njdu9KAT_NCkYrw',
    appId: '1:69808295537:android:5262e893ab74aa2a6e95d0',
    messagingSenderId: '69808295537',
    projectId: 'new-application-2fdd1',
    storageBucket: 'new-application-2fdd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANUSK5lEni8hSPduy9-e5c7M134Ln855A',
    appId: '1:69808295537:ios:70a649632bacc7156e95d0',
    messagingSenderId: '69808295537',
    projectId: 'new-application-2fdd1',
    storageBucket: 'new-application-2fdd1.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANUSK5lEni8hSPduy9-e5c7M134Ln855A',
    appId: '1:69808295537:ios:70a649632bacc7156e95d0',
    messagingSenderId: '69808295537',
    projectId: 'new-application-2fdd1',
    storageBucket: 'new-application-2fdd1.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIHscjlVILrRxwbhlEcgptQq2NZKhxamg',
    appId: '1:69808295537:web:4cd816ada19e7e1c6e95d0',
    messagingSenderId: '69808295537',
    projectId: 'new-application-2fdd1',
    authDomain: 'new-application-2fdd1.firebaseapp.com',
    storageBucket: 'new-application-2fdd1.appspot.com',
    measurementId: 'G-NLD3DDLXHC',
  );
}
